// Benjamin Bowser
// Assignment 12
// CSE270e
// 1/19/19
var rest = require("./api.js");
var http = require("http");
var path = require("path");
var express = require("express");
var bodyParser = require("body-parser");
var app = express();

app.set("views", path.resolve(__dirname, "views"));
app.set("view engine", "ejs");

app.use(bodyParser.urlencoded({ extended: false }));

// Load the index file when / requested
app.get("/", function(req, res) {
	rest.getRovers(function(data) {
		var i;
		var array = [];
		for (i = 0; i < data.rovers.length; i++) {
			array.push(data.rovers[i].name);
		}
	res.render("index", { posts: array });
	});
});

// Load rover page and display list of images (see note below)
app.get("/mars/:rover", function(req, res) {
  var rover = (req.params.rover).toLowerCase();
  var soldate;
  rest.getRovers(function(data) {
  var i;
  for (i = 0; i < data.rovers.length; i++) {
	if ((data.rovers[i].name).toLowerCase() == rover) {
	// This value can differ from the one generated by the getMarsPhotos
	// method. It is because of the NASA API.
	soldate = data.rovers[i].max_sol;
	}
  }
	rest.getMarsPhotos(rover, soldate, function(cb) {
		var array = [];
		var j;
		for (j = 0; j < cb.photos.length; j++) {
			array.push(cb.photos[j].img_src);
		}
	var data = {rover: rover, sol: soldate, maxsol: soldate};
	res.render("mars", { data, posts: array });
	});
  });
});

// Load photos for given soldate (see note below)
app.get("/mars/:rover/:date", function(req, res) {
  var rover = (req.params.rover).toLowerCase();
  var soldate = req.params.date;
  rest.getMarsPhotos(rover, soldate, function(cb) {
	var array = [];
	var i;
	for (i = 0; i < cb.photos.length; i++) {
		array.push(cb.photos[i].img_src);
	}
	// This DOES NOT work with opporunity. Max sol is 5111, but when pressing previous buttons
	// 5110 and 5109 are empty in the API, causing it to hang.
	var data = {rover: rover, sol: soldate, maxsol: cb.photos[0].rover.max_sol };
	res.render("mars", {data, posts: array });
});
});

// Run the server on port 3012
http.createServer(app).listen(3012, function() {
  console.log("Started on port 3012.");
});
